In [2]:
import numpy as np

In [3]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [4]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [5]:
a_list[3]

4

In [6]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [7]:
k_krotka[4]

5

In [9]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [10]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [11]:
n_array = np.array(a_list) # wektor numpy

In [25]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat', 100], dtype=object)

In [13]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [14]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [15]:
studenci_slownik["Zosia"]

22

In [16]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [23]:
for elementy in studenci_slownik.items():
    print(elementy)

('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])


In [24]:
for elementy in studenci_slownik.values():
    print(elementy)

3
5
22
[2, 21]


In [17]:
studenci_slownik["Cuthulu"]= -1000000

In [18]:
studenci_slownik

{123: 123,
 'Igor': 3,
 'Frankek': 5,
 'Zosia': 22,
 'Julia': [2, 21],
 (1, 2): 'Krotka',
 'Cuthulu': -1000000}

In [19]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [20]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 123, 1: 'Igor', 2: 'Frankek', 3: 'Zosia', 4: 'Julia', 5: (1, 2), 6: 'Cuthulu'}


In [21]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [22]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [23]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [24]:
1 in a
"Igor" in studenci_slownik

True

### Własne typy

In [17]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

dodaj_dwie_liczby(2,4)

6

In [26]:
class klassa():
    
    nazwa = "stała"
    
nazwana = klassa()
type(nazwana)
print(nazwana.nazwa)

stała


In [20]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    autor = "Maciek"
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [22]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [18]:
pio_zajecia.dzien

'piatek'

In [14]:
pio_zajecia.ile_zajec

4

In [23]:
pio_zajecia.autor

'Maciek'

In [19]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [33]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [26]:
pio_zajecia.lista_zajec.append("MISPP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP', 'MISPP']


In [27]:
pio_zajecia.ile_mispow()

5

In [95]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [33]:
class DzienZajecFM(DzienZajec):
    
    def kocham_mispy(self):
        print("tak średnio kocham mispy")
    
        kocham_mispy()

In [85]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [105]:
print(pio_zajecia.ile_zajec)

5


In [108]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [109]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [112]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [113]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [114]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

In [51]:
class NumerTelefonu:
    
    #inicjalizacja klasy
    def __init__(self, nrTel):
        self.nrTelefonu = nrTel
        if len(self.nrTelefonu) ==9:
            print("prawidlowy numer.")
        else:
            print("nieprawidłowy numer.")

    #zwraca miasto na podstawie nr kierunkowego        
    def wojewodztwo(self):
        kierunkowy = self.nrTelefonu[0]+self.nrTelefonu[1]
        nrKierunkowe = {"42":"Łódź", "41":"Kielce", "22":"Warszawa"}
        try:
            kier_miasto = nrKierunkowe[kierunkowy]
        except KeyError:
            kier_miasto = "inne"
        return kier_miasto
    
    
    def __repr__(self):
        cyfry = ["zero","jeden","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć"]
        
        numerSlownie = []
        
        for a in self.nrTelefonu:
            numerSlownie.append(cyfry[int(a)])
        return numerSlownie
        


In [52]:
numer_lodz = NumerTelefonu("42277868")

nieprawidłowy numer.


In [53]:
numer_lodz.wojewodztwo()

'Łódź'

In [54]:
print(numer_lodz)

TypeError: __str__ returned non-string (type list)

In [55]:
numer_lodz.numerSlownie

AttributeError: 'NumerTelefonu' object has no attribute 'numerSlownie'